---
title: "comfamInterpretation"
output: html_document
---

## The input to the comfam function
```{r}
suppressPackageStartupMessages({
  library(neuroCombat)
  library(ComBatFamily)
})

# generate toy dataset
set.seed(8888)
n <- 20
p <- 5
bat <- as.factor(c(rep("a", n/2), rep("b", n/2)))
q <- 2
covar <- matrix(rnorm(n*q), n, q)
colnames(covar) <- paste0("x", 1:q)
data <- data.frame(matrix(rnorm(n*p), n, p))

# cf <- comfam(data, bat, covar, lm, formula = y ~ x1 + x2)
```

## The comfam function definition
```{r}
comfam <- function(data, bat, covar = NULL, model = lm, formula = NULL,
                   eb = TRUE, robust.LS = FALSE, ref.batch = NULL, ...) {
  

  # Data details and formatting
  data <- as.matrix(data)
  n <- nrow(data)
  p <- ncol(data)

  # ensure things have been provided correctly
  if ((p == 1) & eb) {
    warning("EB step skipped for univariate data.")
    eb <- FALSE
  }

  if (!is.null(ref.batch)) {
    if (!(ref.batch %in% levels(bat))) {
      stop("Reference batch must be in the batch levels")
    }
    ref <- bat == ref.batch
    nref <- sum(ref)
  }
  
  # Specify robust location/scale estimators
  if (robust.LS) {
    loc <- median
    scl <- .biweight_midvar
  } else {
    loc <- mean
    scl <- var
  }
  
  # creates matrix of binary batch membership for each subject (One hot).
  # batches describes who is in which batch.
  # n_batches stores the size of each batch.
  bat <- droplevels(bat)
  batch <- model.matrix(~ -1 + bat)
  batches <- lapply(levels(bat), function(x) which(bat == x))
  n_batches <- sapply(batches, length)

   #### Fit specified models ####
  if (is.null(covar)) {
    mod <- data.frame(I(batch))
  } else {
    mod <- data.frame(covar, I(batch))
  }
  
  
  
  if (is.null(covar) | is.null(formula)) {
    formula <- y ~ 1
  }

  # case when using nlme::lme
  if (hasArg("fixed")) {
    fits <- apply(data, 2, function(y) {
      dat <- data.frame(y = y, mod)

      addargs <- list(...)
      addargs$fixed <- NULL

      # include batch in formula to target pooled mean/variance
      bat_formula <- update(formula, ~ . + batch + -1)
      do.call(model, c(list(fixed = bat_formula, data = dat), addargs))
    })
  } else {
    fits <- apply(data, 2, function(y) {
      # data frame combining the current column with the mod data frame.
      # mod has both covariates and batch!
      # so this data frame dat is column of data plus mod.
      dat <- data.frame(y = y, mod)

      # include batch in formula to target pooled mean/variance
      # remove intercept
      bat_formula <- update(formula, ~ . + batch + -1)
      do.call(model, list(formula = bat_formula, data = dat, ...))
    })
  }
  
    #### Standardize the data ####
  # Model matrix for obtaining pooled mean
  pmod <- mod
  # contains a matrix
  pmod$batch[] <- matrix(n_batches/n, n, nlevels(bat), byrow = TRUE)
  

  # If there IS a Reference batch
  if (!is.null(ref.batch)) {
    pmod$batch[] <- 0
    pmod$batch[,which(levels(bat) == ref.batch)] <- 1
  }
  
  stand_mean <- sapply(fits, predict, newdata = pmod, type = "response")
  resid_mean <- sapply(fits, predict, newdata = mod, type = "response")
  
  # if there is a reference batch.
  if (!is.null(ref.batch)) {
    var_pooled <- apply((data - resid_mean)[ref, , drop = FALSE], 2, scl) *
      (nref - 1)/nref
  # no reference batch:
  } else {
    # scl = variance
    # the factor (n-1)/n is saying this is the population variance
    var_pooled <- apply(data - resid_mean, 2, scl) * (n - 1)/n
  }

  if (hasArg("sigma.formula")) {
    sd_mat <- sapply(fits, predict, newdata = pmod, what = "sigma",
                     type = "response")
  } else {
    # same standard deviation across batches
    sd_mat <- sapply(sqrt(var_pooled), rep, n)
  }

  data_stand <- (data-stand_mean)/sd_mat
  #### Obtain location and scale adjustments ####
  gamma_hat <- Reduce(rbind, by(data_stand, bat, function(x) apply(x, 2, loc)))
  delta_hat <- Reduce(rbind, by(data_stand, bat, function(x) apply(x, 2, scl)))

  rownames(gamma_hat) <- rownames(delta_hat) <- levels(bat)
  
  # Empirical Bayes adjustments
  if (eb) {
    gamma_star <- NULL
    delta_star <- NULL

    for (i in 1:nlevels(bat)) {
      n_b <- n_batches[i]

      # method of moments estimates
      g_bar <- mean(gamma_hat[i,])
      g_var <- var(gamma_hat[i,])

      d_bar <- mean(delta_hat[i,])
      d_var <- var(delta_hat[i,])

      d_a <- (2 * d_var + d_bar^2)/d_var
      d_b <- (d_bar * d_var + d_bar^3)/d_var

      # adjust within batch
      bdat <- data_stand[batches[[i]],]
      g_orig <- gamma_hat[i,]
      g_old  <- gamma_hat[i,]
      d_old  <- delta_hat[i,]

      change_old <- 1
      change <- 1
      count  <- 0
      while(change > 10e-5){
        g_new <- (n_b*g_var*g_orig + d_old*g_bar)/(n_b*g_var + d_old)

        if (robust.LS) {
          sum2 <- (n_b-1) * sapply(1:p, function(v) {
            .biweight_midvar(bdat[,v], g_new[v])})
        } else {
          sum2   <- colSums(sweep(bdat, 2, g_new)^2)
        }

        d_new <- (sum2/2 + d_b)/(n_b/2 + d_a - 1)

        change <- max(abs(g_new - g_old)/g_old, abs(d_new - d_old)/d_old)

        if (count > 30) {
          if (change > change_old) {
            warning("Empirical Bayes step failed to converge after 30 iterations,
    	            using estimate before change between iterations increases.")
            break
          }
        }

        g_old <- g_new
        d_old <- d_new

        change_old <- change
        count <- count+1
      }

      # (m,p) arrays by the end of the for loop.
      # at first iteration, (1,p), at second, (2, p), etc
      gamma_star <- rbind(gamma_star, g_new)
      delta_star <- rbind(delta_star, d_new)
    }

    rownames(gamma_star) <- rownames(gamma_hat)
    rownames(delta_star) <- rownames(delta_hat)
  } else {
    gamma_star <- gamma_hat
    delta_star <- delta_hat
  }
  
  
  data_nb <- data_stand
  
  #### Harmonize the data ####
  # Remove batch effects
  data_nb <- data_stand
  for (i in 1:nlevels(bat)) {
    # get the rows in data_stand corresponding to batch i.
    # subtract column wise the values of gamma_star[i, ]
    data_nb[batches[[i]],] <- sweep(data_nb[batches[[i]],, drop = FALSE], 2,
                                    gamma_star[i,], "-")
    data_nb[batches[[i]],] <- sweep(data_nb[batches[[i]],, drop = FALSE], 2,
                                    sqrt(delta_star[i,]), "/")
  }
  # Reintroduce covariate effects
  data_combat <- data_nb*sd_mat + stand_mean

  if (!is.null(ref.batch)) {
    data_combat[ref,] <- data[ref,]
  }

  estimates <-  list(
    stand.mean = stand_mean,
    stand.sd = sd_mat,
    var.pooled = var_pooled,
    gamma.hat = gamma_hat,
    delta.hat = delta_hat,
    gamma.star = gamma_star,
    delta.star = delta_star
  )

  batch_info <- list(
    batch = bat,
    batch.mod = pmod$batch,
    ref.batch = ref.batch
  )

  out <- list(dat.combat = data_combat, batch.info = batch_info,
              fits = fits, estimates = estimates)
  class(out) <- "comfam"
  out
}
```

```{r}
result <- comfam(data, bat, covar, lm, formula = y ~ x1 + x2)
```

## Generate some new data 
```{r}
#I want some of the batches to over lap, and some to be new.
suppressPackageStartupMessages({
  library(neuroCombat)
  library(ComBatFamily)
})

# generate toy dataset
set.seed(8888)
n <- 40
p <- 5
bat <- as.factor(c(rep("b", n/4), rep("c", n/4), rep("d", n/4), rep("e", n/4)))
q <- 2
covar <- matrix(rnorm(n*q), n, q)
colnames(covar) <- paste0("x", 1:q)
data <- data.frame(matrix(rnorm(n*p), n, p))

```


```{r}
# default names are X1, X2, etc
data

```
```{r}
covar
```





```{r}
predict.comfam <- function(object, newdata, newbat, newcovar = NULL,
                           robust.LS = FALSE, eb = TRUE, ...) {


  data <- as.matrix(newdata)
  n <- nrow(data)
  p <- ncol(data)
  
  if ((p == 1) & eb) {
    warning("EB step skipped for univariate data.")
    eb <- FALSE
  }
  
  # Specify robust location/scale estimators
  if (robust.LS) {
    loc <- median
    scl <- .biweight_midvar
  } else {
    loc <- mean
    scl <- var
  }

  bat <- object$batch.info$batch
  batch_mod <- object$batch.info$batch.mod
  stand_mean <- object$estimates$stand.mean
  var_pooled <- object$estimates$var.pooled
  gamma_hat <- object$estimates$gamma.hat
  delta_hat <- object$estimates$delta.hat
  gamma_star <- object$estimates$gamma.star
  delta_star <- object$estimates$delta.star
  fits <- object$fits
  
   #### Match new batches to old batches ####
  known <- rownames(gamma_hat)
  bat <- droplevels(bat)
  newbat <- droplevels(newbat)
  bat_levels <- union(known, levels(newbat))
  newbat_app <- factor(newbat, bat_levels)
  batches <- lapply(levels(newbat_app), function(x) which(newbat_app == x))
  
  # new batches to estimate/adjust
  #bat_levels are a b c d. setdiff(levels(newbat),known) is c("c", "d")
  #which(bat_levels in c("c","d")) is 3, 4
  newbat_est <- which(bat_levels %in% setdiff(levels(newbat), known))
  # 2 3 4
  newbat_adj <- which(bat_levels %in% levels(newbat))
  
   #### Standardize the data ####
  # resize batch_mod
  #batch_mod has the same elements on every row. 
  #So taking batch_mod[1, ], n just gets enough rows for the new data
  # We pulled batch_mod from object$batch.info$batch.mod
  batch <- matrix(batch_mod[1,], n, nlevels(bat), byrow = TRUE)
  
  # pmod is now dim(n, num covariates + num batches)?
  if (is.null(newcovar)) {
    pmod <- data.frame(I(batch))
  } else {
    pmod <- data.frame(newcovar, I(batch))
  }
  

  # why does pmod not have rows 0.33 0.33 0.33?
  # perhaps if I add a third NEW batch, then it will.
  stand_mean <- sapply(fits, predict, newdata = pmod, type = "response", ...)
  if (hasArg("sigma.formula")) {
    sd_mat <- sapply(fits, predict, newdata = pmod, what = "sigma",
                     type = "response", ...)
  } else {
    sd_mat <- sapply(sqrt(var_dpooled), rep, n)
  }
  
  data_stand <- (data - stand_mean)/sd_mat

  #### Obtain location and scale adjustments ####
  # get naive estimates for new batches
  for (i in newbat_est) {
    gamma_hat <- rbind(gamma_hat,
                       apply(data_stand[batches[[i]],, drop = FALSE], 2, loc))
    delta_hat <- rbind(delta_hat,
                       apply(data_stand[batches[[i]],, drop = FALSE], 2, scl))
  }

  rownames(gamma_hat) <- rownames(delta_hat) <- bat_levels
  
    # Empirical Bayes adjustments for new batches
  if (eb) {
    for (i in newbat_est) {
      n_b <- length(batches[[i]])

      # method of moments estimates
      g_bar <- mean(gamma_hat[i,])
      g_var <- var(gamma_hat[i,])
      d_bar <- mean(delta_hat[i,])
      d_var <- var(delta_hat[i,])
      d_a <- (2 * d_var + d_bar^2)/d_var
      d_b <- (d_bar * d_var + d_bar^3)/d_var

      # adjust within batch
      bdat <- data_stand[batches[[i]],]
      g_orig <- gamma_hat[i,]
      g_old  <- gamma_hat[i,]
      d_old  <- delta_hat[i,]

      change_old <- 1
      change <- 1
      count  <- 0
      # looping through adjustments
      while(change > 10e-5){
        g_new <- (n_b*g_var*g_orig + d_old*g_bar)/(n_b*g_var + d_old)

        if (robust.LS) {
          sum2 <- (n_b-1) * sapply(1:p, function(v) {
            .biweight_midvar(bdat[,v], g_new[v])})
        } else {
          sum2   <- colSums(sweep(bdat, 2, g_new)^2)
        }

        d_new <- (sum2/2 + d_b)/(n_b/2 + d_a - 1)

        change <- max(abs(g_new - g_old)/g_old, abs(d_new - d_old)/d_old)

        if (count > 30) {
          if (change > change_old) {
            warning("Empirical Bayes step failed to converge after 30 iterations,
    	            using estimate before change between iterations increases.")
            break
          }
        }

        g_old <- g_new
        d_old <- d_new

        change_old <- change
        count <- count+1
      }

      # This executes i times inside the loop.
      # g_new is 1,p array
      gamma_star <- rbind(gamma_star, g_new)
      delta_star <- rbind(delta_star, d_new)
    }

    rownames(gamma_star) <- rownames(gamma_hat)
    rownames(delta_star) <- rownames(delta_hat)
  } else {
    gamma_star <- gamma_hat
    delta_star <- delta_hat
  }
  
  #### Harmonize the data ####
  # Remove batch effects
  
  # all that remains here is just gamma_ig + delta_ig\epsilon ijg
  data_nb <- data_stand
  for (i in newbat_adj) {
    # After subtraction, all that remains is delta_ig\epsilon ijg
    data_nb[batches[[i]],] <- sweep(data_nb[batches[[i]],, drop = FALSE], 2,
                                    gamma_star[i,], "-")
    # after division, all that remains is just epsilon ijg
    data_nb[batches[[i]],] <- sweep(data_nb[batches[[i]],, drop = FALSE], 2,
                                    sqrt(delta_star[i,]), "/")
  }
  
  # Reintroduce covariate effects
  # divided out the sd_mat - so must multiply by it to get everything on the same scale.
  # now we add back stand mean which is our best guess of the no scanner effect.
  data_combat <- data_nb*sd_mat + stand_mean
  
  browser()
  return(mget(ls()))

}
```

```{r}

pred_result <- predict.comfam(result, data, bat, covar)

```






```{r}
?sapply
?which
```

```{r}

?predict
```

```{r}

data
```

```{r}


```

```{r}


```

```{r}


```
